# app/config/security.yml

security:
  encoders:
    Symfony\Component\Security\Core\User\User: plaintext
    OC\UserBundle\Entity\User: plaintext

  role_hierarchy:
    # Un admin hérite des droits d'auteur et de modérateur
    ROLE_ADMIN:       [ROLE_AUTEUR, ROLE_MODERATEUR]
    # On garde ce rôle superadmin, il nous resservira par la suite
    ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

  providers:
    # … vous pouvez supprimer le fournisseur « in_memory »
    # Et voici notre nouveau fournisseur :
    main:
      entity:
        class:    OC\UserBundle\Entity\User
        property: username

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      pattern:      ^/
      anonymous:    true
      provider:     main
      form_login:
        login_path: login
        check_path: login_check
      logout:
        path:       logout
        target:     /platform

  access_control:
    - { path: ^/admin, roles: ROLE_ADMIN }
