# src/OC/PlatformBundle/Resources/config/routing.yml

oc_platform_homepage:
    path:     /
    defaults: { _controller: OCPlatformBundle:Default:index }
hello_the_world:
    path:     /hello-world
    defaults: { _controller: OCPlatformBundle:Advert:index }
